language: c
sudo: false
addons:
  apt:
    packages:
    - yasm
    - bc
compiler:
  - clang
  - gcc
script:
  - mkdir ~/libav-samples
  - ./configure --samples=${HOME}/libav-samples
  - make -j 8
  - make fate-rsync
  - make fate -j 8
